# Generated by Django 4.1.3 on 2022-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Password2', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Email',
        ),
        migrations.AddField(
            model_name='payment',
            name='Email_card',
            field=models.CharField(default='email', max_length=200),
        ),
    ]
