# Generated by Django 4.1.3 on 2023-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0003_rename_customer_login_customerlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Email_card',
            field=models.CharField(max_length=200),
        ),
    ]
