# Generated by Django 4.1.3 on 2023-01-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0004_alter_payment_email_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='CVV_card',
            new_name='CVVcard',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Card_number',
            new_name='Cardnumber',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Email_card',
            new_name='Emailcard',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Expiry_card',
            new_name='Expirycard',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Name_Card',
            new_name='NameCard',
        ),
    ]
